addrs: "0.0.0.0:8080"

solana:
    read_rpcs:
        -   url: https://api.devnet.solana.com
            ratelimit: 4 # requests per second
    write_rpcs:
        -   url: https://api.devnet.solana.com
            ratelimit: 4 # requests per second
    reader_concurrency: 32
