[package]
name = "mootvote"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "mootvote"

[features]
default = ["no-idl"]
anchor-debug = ["anchor-lang/anchor-debug"]
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = { version = "1.0", features = ["init-if-needed"] }
groth16-solana = "0.2"
solana-bn254 = "3"
solana-invoke = "0.5"
solana-poseidon = "4"
solana-system-interface = "2"
zk-relayer = { path = "../../programs/zk-relayer", features = ["cpi"] }
